package cs3500.music.tests;

import java.io.*;

import cs3500.music.MusicEditor;
import org.junit.*;
import javax.sound.midi.InvalidMidiDataException;

/**
 * Created by mattmorgan on 3/23/16.
 */


/**
 * test the console view of a piece of music my matching Outputstreams with what we expect
 */
public class ConsoleViewTest {
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void cleanUpStreams() {
    System.setOut(null);
  }

  /**
   * test mary had a little lamb in the consol view
   */
  @Test
  public void testConsoleView() {
    String[] inputs = new String[2];
    inputs[0] = "mary-little-lamb.txt";
    inputs[1] = "console";
    try {
      MusicEditor.main(inputs);
    } catch (IOException e) {
      e.printStackTrace();
    } catch (InvalidMidiDataException e) {
      e.printStackTrace();
    }
    Assert.assertEquals("    C0 C#0  D0 D#0  E0  F0 F#0  G0 G#0  A0 A#0  B0  C1 C#1  D1 D#1  E1  "
      + "F1 F#1  G1 G#1  A1 A#1  B1  C2 C#2  D2 D#2  E2  F2 F#2  G2 G#2  A2 A#2  B2  C3 C#3  D3 D#3"
      + "  E3  F3 F#3  G3 G#3  A3 A#3  B3  C4 C#4  D4 D#4  E4  F4 F#4  G4 G#4  A4 A#4  B4  C5 C#5 "
      + " D5 D#5  E5  F5 F#5  G5\n"
      + " 0                                                                                       "
      + "                                                                                          "
      + "                                             X                                   X       "
      + "     \n"
      + " 1                                                                                      "
      + "                                                                                        "
      + "                                                |                                   |   "
      + "         \n"
      + " 2                                                                                      "
      + "                                                                                         "
      + "                                               |                           X             "
      + "       \n"
      + " 3                                                                                       "
      + "                                                                                         "
      + "                                              |                           |            "
      + "        \n"
      + " 4                                                                                       "
      + "                                                                                         "
      + "                                              |                   X                       "
      + "     \n"
      + " 5                                                                                       "
      + "                                                                                                                                       |                   |                            \n"
      + " 6                                                                                       "
      + "                                                                                                                                       |                           X                    \n"
      + " 7                                                                                      "
      + "                                                                                                                                                                    |                    \n"
      + " 8                                                                                      "
      + "                                                                                                                                        X                                   X            \n"
      + " 9                                                                                      "
      + "                                                                                        "
      + "                                                |                                   |    "
      + "        \n"
      + "10                                                                                      "
      + "                                                                                                                                        |                                   X            \n"
      + "11                                                                                      "
      + "                                                                                        "
      + "                                                |                                   |   "
      + "         \n"
      + "12                                                                                     "
      + "                                                                                        "
      + "                                                 |                                   X   "
      + "         \n"
      + "13                                                                                                                                                                                                                              |                                   |            \n"
      + "14                                                                                        "
      + "                                                                                          "
      + "                                            |                                   |       "
      + "     \n"
      + "15                                                                                       "
      + "                                                                                         "
      + "                                                                                         "
      + "      \n"
      + "16                                                                                      "
      + "                                                                                         "
      + "                                               X                           X              "
      + "      \n"
      + "17                                                                                       "
      + "                                                                                         "
      + "                                              |                           |               "
      + "     \n"
      + "18                                                                                       "
      + "                                                                                         "
      + "                                              |                           X               "
      + "     \n"
      + "19                                                                                        "
      + "                                                                                                                                      |                           |                    \n"
      + "20                                                                                       "
      + "                                                                                         "
      + "                                              |                           X              "
      + "      \n"
      + "21                                                                                       "
      + "                                                                                         "
      + "                                              |                           |              "
      + "      \n"
      + "22                                                                                       "
      + "                                                                                         "
      + "                                              |                           |              "
      + "      \n"
      + "23                                                                                       "
      + "                                                                                         "
      + "                                              |                           |              "
      + "      \n"
      + "24                                                                                       "
      + "                                                                                         "
      + "                                              X                                   X      "
      + "      \n"
      + "25                                                                                       "
      + "                                                                                         "
      + "                                              |                                   |      "
      + "      \n"
      + "26                                                                                       "
      + "                                                                                         "
      + "                                                                                         "
      + "     X\n"
      + "27                                                                                       "
      + "                                                                                         "
      + "                                                                                         "
      + "     |\n"
      + "28                                                                                      "
      + "                                                                                        "
      + "                                                                                        "
      + "        X\n"
      + "29                                                                                      "
      + "                                                                                        "
      + "                                                                                       "
      + "         |\n"
      + "30                                                                                    "
      + "                                                                                      "
      + "                                                                                      "
      + "              |\n"
      + "31                                                                                    "
      + "                                                                                      "
      + "                                                                                     "
      + "               |\n"
      + "32                                                                                   "
      + "                                                                                     "
      + "                                                      X                              "
      + "     X            \n"
      + "33                                                                                   "
      + "                                                                                      "
      + "                                                     |                                "
      + "   |            \n"
      + "34                                                                                    "
      + "                                                                                      "
      + "                                                    |                           X     "
      + "               \n"
      + "35                                                                                    "
      + "                                                                                      "
      + "                                                    |                           |     "
      + "               \n"
      + "36                                                                                    "
      + "                                                                                      "
      + "                                                    |                   X             "
      + "               \n"
      + "37                                                                                    "
      + "                                                                                      "
      + "                                                    |                   |             "
      + "               \n"
      + "38                                                                                   "
      + "                                                                                     "
      + "                                                      |                           X  "
      + "                  \n"
      + "39                                                                                   "
      + "                                                                                     "
      + "                                                      |                           |  "
      + "                  \n"
      + "40                                                                                   "
      + "                                                                                     "
      + "                                                      X                              "
      + "     X            \n"
      + "41                                                                                   "
      + "                                                                                     "
      + "                                                      |                              "
      + "     |            \n"
      + "42                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  X            \n"
      + "43                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  |            \n"
      + "44                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  X            \n"
      + "45                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  |            \n"
      + "46                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  X            \n"
      + "47                                                                                    "
      + "                                                                                      "
      + "                                                    |                                 "
      + "  |            \n"
      + "48                                                                                    "
      + "                                                                                      "
      + "                                                    X                           X     "
      + "               \n"
      + "49                                                                                   "
      + "                                                                                     "
      + "                                                      |                           |  "
      + "                  \n"
      + "50                                                                                                                                                                                                                              |                           X                    \n"
      + "51                                                                                   "
      + "                                                                                     "
      + "                                                      |                           |  "
      + "                  \n"
      + "52                                                                                   "
      + "                                                                                    "
      + "                                                       |                                "
      + "   X            \n"
      + "53                                                                                   "
      + "                                                                                      "
      + "                                                     |                                 "
      + "  |            \n"
      + "54                                                                                    "
      + "                                                                                     "
      + "                                                     |                           X    "
      + "                \n"
      + "55                                                                                 "
      + "                                                                                   "
      + "                                                          |                        "
      + "   |                    \n"
      + "56                                                                                  "
      + "                                                                                    "
      + "                                            X                               X        "
      + "                    \n"
      + "57                                                                                   "
      + "                                                                                      "
      + "                                         |                               |           "
      + "                 \n"
      + "58                                                                                    "
      + "                                                                                      "
      + "                                        |                               |           "
      + "                 \n"
      + "59                                                                                   "
      + "                                                                                      "
      + "                                         |                               |           "
      + "                 \n"
      + "60                                                                                   "
      + "                                                                                     "
      + "                                          |                               |        "
      + "                    \n"
      + "61                                                                                 "
      + "                                                                                   "
      + "                                              |                               |   "
      + "                         \n"
      + "62                                                                                 "
      + "                                                                                   "
      + "                                              |                               |     "
      + "                       \n"
      + "63                                                                                 "
      + "                                                                                  "
      + "                                               |                               |  "
      + "                          ", outContent.toString());
  }
}
